In [42]:
import numpy as np
file = './commits.txt'

In [61]:
file_list_for_all_commits = [] #array of file_list arrays
file_list = [] #of a single commit
all_files = [] #every file that ever appeared in all commits

with open(file) as f:
    
    while(1):
        #read line
        line = f.readline()
        
        #eof, add last commit to array
        if not line:
            file_list_for_all_commits.append(file_list)
            break
        
        #git log formatting allows to separate commits by an empty new line
        if line == '\n':
            file_list_for_all_commits.append(file_list)
            continue
            
        #removes \n from file names
        line = line.rstrip('\n')
        
        #if it is a new commit, clean file list 
        if(line == '###NEW_COMMIT###'):
            file_list = []
            continue

        #it's a file! separeted by commmit there is no duplicates
        file_list.append(line)
        
        #listing all files
        if line not in all_files:
            all_files.append(line)
    
    #graph
    logical_coupling = np.zeros((len(all_files), (len(all_files))))
    
    #fills graph with how many times each two files appear together
    for commit in file_list_for_all_commits:
        for file1 in commit:
            for file2 in commit:
                if(file1 == file2):
                    continue
                logical_coupling[all_files.index(file1)][all_files.index(file2)] += 1
    
    #ill start answering questions here but not now
    maxi = np.amax(logical_coupling)
    location = np.where(logical_coupling == np.amax(logical_coupling))
    print(location)
    print(maxi)
    
    print(all_files[435], all_files[450])



    
    
        

[[ 0.  1.  0. ...  0.  0.  0.]
 [ 1.  0. 16. ...  0.  0.  0.]
 [ 0. 16.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
(array([435, 450]), array([450, 435]))
58.0
12.0/apache/Dockerfile 12.0/fpm/Dockerfile
